### ISSUE TITLE
app.use(i18n(options)); doesn't reach all the routes

### ISSUE THREAD

**Issue by gsarme** [koalazak/i18n-express#16]
I put this in my index.js but it doesnt' reach all the routes that I have in the project

```
var i18n=require("i18n-express");
var geolang=require("geolang-express");

 app.use(geolang({
  siteLangs: ["en","it"],
  cookieLangName: 'ulang'
}));

app.use(i18n({
  translationsPath: path.join(__dirname, 'i18n'),
  siteLangs: ["en","it"],
  cookieLangName: 'ulang',
  textsVarName: 'translation',
  paramLangName: 'clang'
}));
```

If I try to use `<%=translation.ADD_APP%>` in my html it gives me this error:

```
ReferenceError: /Users/web/Desktop/node/pusha/views/apps/add_new_app.ejs:13
    11|               <div class="container">
    12|                 <form action="/apps" method="post">
 >> 13|                   <h3><%=translation.ADD_APP%></h3>
    14|                   <p><strong>Name:</strong> <input type="text" name = "name"></p>
    15|                   <br>
    16|               <!-- --------------------------------- -->

translation is not defined
    at eval (eval at compile (/Users/web/Desktop/node/pusha/node_modules/ejs/lib/ejs.js:524:12), <anonymous>:43:25)
    at returnedFn (/Users/web/Desktop/node/pusha/node_modules/ejs/lib/ejs.js:555:17)
    at tryHandleCache (/Users/web/Desktop/node/pusha/node_modules/ejs/lib/ejs.js:203:34)
    at View.exports.renderFile [as engine] (/Users/web/Desktop/node/pusha/node_modules/ejs/lib/ejs.js:412:10)
    at View.render (/Users/web/Desktop/node/pusha/node_modules/express/lib/view.js:128:8)
    at tryRender (/Users/web/Desktop/node/pusha/node_modules/express/lib/application.js:640:10)
    at EventEmitter.render (/Users/web/Desktop/node/pusha/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/web/Desktop/node/pusha/node_modules/express/lib/response.js:966:7)
    at /Users/web/Desktop/node/pusha/routes/apps.js:124:9
    at Layer.handle [as handle_request] (/Users/web/Desktop/node/pusha/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/web/Desktop/node/pusha/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/web/Desktop/node/pusha/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/web/Desktop/node/pusha/node_modules/express/lib/router/layer.js:95:5)
    at /Users/web/Desktop/node/pusha/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/web/Desktop/node/pusha/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/web/Desktop/node/pusha/node_modules/express/lib/router/index.js:275:10)
```

**Comment by gsarme** [comment]
I solved. I put the code in the wrong file.
