### ISSUE TITLE
Error: Cannot find module './public/i18n/en.json'

### ISSUE THREAD

**Issue by frunzisss** [koalazak/i18n-express#5]
It's very interesting because my file is there. And if I change it's name it will give me an error saying the same thing with the new name of the file.

Error: Cannot find module './public/i18n/en.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at loadLangJSONFiles (C:\Users\Adi\Desktop\7-nodejs-express-web-applications-m7-exercise-files\codeEnd\library\node_modules\i18n-express\index.js:49:66)
    at module.exports (C:\Users\Adi\Desktop\7-nodejs-express-web-applications-m7-exercise-files\codeEnd\library\node_modules\i18n-express\index.js:79:19)
    at Object.<anonymous> (C:\Users\Adi\Desktop\7-nodejs-express-web-applications-m7-exercise-files\codeEnd\library\app.js:61:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

**Comment by koalazak** [comment]
Hi @frunzisss,

can you showme your i18n-express options object?
what version of node.js? and OS?

thanks

**Comment by frunzisss** [comment]
/*app.use(i18n({
    translationsPath: "./public/i18n", // <--- use here. Specify translations files path. 
    siteLangs: ["en", "ro"]
}));*/  
___________________________________________________________________________________________
Version: 6.4.8
___________________________________________________________________________________________
OS:  10 Home, 64

**Comment by koalazak** [comment]
try to use `path.join()` to get actual dir and use correct path (complete with the path from tue file when you have this lines):

```
app.use(i18n({
  translationsPath: path.join(__dirname, 'public/i18n'),
  siteLangs: ["en", "ro"]
}));
```
maybe fsevents is used on require ( I use require to load json files) and its incompatible with windows (https://github.com/strongloop/fsevents/issues/134).

Y will try on windows later.
Please, let me known if with path.join() works.

**Comment by koalazak** [comment]
I'll close this for now. Please reply if you still experience issues, and I'll reopen the issue.
