### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'ulang' in undefined

### ISSUE THREAD

**Issue by lebesnec** [koalazak/i18n-express#6]
I have the following error when I try to use i18n-express in my application :

```
TypeError: Cannot use 'in' operator to search for 'ulang' in undefined
    at getLangFromCookie (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\i18n-express\index.js:20:26)
    at i18n (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\i18n-express\index.js:85:21)
    at Layer.handle [as handle_request] (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\express\lib\router\index.js:271:10)
    at expressInit (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\express\lib\middleware\init.js:33:5)
    at Layer.handle [as handle_request] (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\express\lib\router\index.js:312:13)
TypeError: C:\Users\JXPK7564\Documents\GitHub\olaf-portal\views\error.ejs:1
 >> 1| <% include partials/header %>
    2|
    3|
    4|

esc is not a function
    at rethrow (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\ejs\lib\ejs.js:285:18)
    at eval (eval at compile (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\ejs\lib\ejs.js:524:12), <anonymous>:30:9)
    at eval (eval at compile (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\ejs\lib\ejs.js:524:12), <anonymous>:32:10)
    at returnedFn (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\ejs\lib\ejs.js:555:17)
    at tryHandleCache (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\ejs\lib\ejs.js:203:34)
    at View.exports.renderFile [as engine] (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\ejs\lib\ejs.js:412:10)
    at View.render (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\express\lib\view.js:126:8)
    at tryRender (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\express\lib\application.js:639:10)
    at EventEmitter.render (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\express\lib\application.js:591:3)
    at ServerResponse.render (C:\Users\JXPK7564\Documents\GitHub\olaf-portal\node_modules\express\lib\response.js:960:7)
```

my code looks like this :

```
var i18n	= require("i18n-express");
...
app.use(i18n({
	translationsPath: __dirname + '/i18n',
	siteLangs: ['en']
}));
```

best regards,

**Comment by lebesnec** [comment]
it looks like cookie-parser is mandatory if you want to use i18n-express :

`app.use(cookieParser()); `
